### ISSUE TITLE
distilled module

### ISSUE THREAD

**Issue by ksh11023** [SirJamie/sgm3d#3]
Hello,

Thank you for the nice work!

In detectors_template.py, I could not import distilled_modules file
Where can I find distilled_modules?

<img width="481" alt="스크린샷 2022-08-20 오후 4 53 48" src="https://user-images.githubusercontent.com/50094436/185735434-a0db4e81-7ec2-405a-94a3-c419611a0570.png">

Thank you!

**Comment by zhouzheyuan** [comment]
Hello,

I have update the code, it should be under `pcdet/models/distilled_modules/`.

**Comment by ksh11023** [comment]
Thank you for the swift reply!
