### ISSUE TITLE
本实验关于LYFT数据集的使用咨询

### ISSUE THREAD

**Issue by xiaoxusanheyi** [SirJamie/sgm3d#8]
你好，作者对于本实验的LYFT数据集验证那个实验，GitHub没有说，可以具体说一下怎么用lyft数据集去实现TABLE VI吗？期待你的回复

**Comment by zhouzheyuan** [comment]
Hi，感谢你对我们工作的关注！

Lyft数据集组织方式与 nuScenes 相同，我们通过nuScenes提供的export_kitti工具将Lyft转换为KITTI格式后进行相应的训练和测试。
另外，在转换过程中请特别注意坐标系的变化。
